### ISSUE TITLE
标题无法修改

### ISSUE THREAD

**Issue by RUSRUSHB** [a-kkiri/CUMCM-typst-template#2]
![屏幕截图 2024-08-20 145904](https://github.com/user-attachments/assets/3159da04-634d-47c0-90c5-b69b8db6e2eb)

修改title后PDF中的标题没有变化。其他修改都是能够正常渲染的。

**Comment by a-kkiri** [comment]
谢谢你的Issue，我将会在下一个版本中修复该问题。

**Comment by a-kkiri** [comment]
你好，目前我已将更改提交到 [typst/packages](https://github.com/typst/packages/pull/895)。等待审核完成，在 WebAPP 中修改 `main.typ` 第一行的版本号为 0.3.0 就可以应用更改了。

**Comment by a-kkiri** [comment]
再次感谢你提交的 Issue，目前更改已经被合并，并且 Typst Universe 中已更新。请你更新为最新版本 0.3.0，稍后我将关闭该 Issue。

**Comment by RUSRUSHB** [comment]
非常感谢！已经可以正常使用了
